### ISSUE TITLE
jazz-plugin/linux incompatible with Qt-based browsers?

### ISSUE THREAD

**Issue by RJVB** [jazz-soft/jazz-soft.github.io#1]
Hi,

I hope I interpreted "online support for other projects" correctly, if not I'll still have brought something to your attention.

The current jazz-plugin extension appears to be incompatible with Qt-based browsers (QtWebKit and QtWebEngine). It simply fails to load because of unsatisfied references to GTk and GDk functions:

```
not loaded: /usr/lib/mozilla/plugins/Jazz-Plugin.so because "Cannot load library /usr/lib/mozilla/plugins/Jazz-Plugin.so: (/usr/lib/mozilla/plugins/Jazz-Plugin.so: undefined symbol: gdk_pango_context_get_for_screen)"
```

**Comment by jazz-soft** [comment]
Thank you for letting me know.
Did you try it on Mac/Windows ?
I'll see what I can do, but that is not on the top of my priority list.

**Comment by RJVB** [comment]
>Did you try it on Mac/Windows ?

I've installed it on Mac and not seen any comparable errors. I was hoping it would allow in-browser playback of MIDI "illustrations" on Wikipedia.org, but I couldn't get that to work in any browser on Mac or Linux so I guess it must be something with how the site exposes the content.

>I'll see what I can do, but that is not on the top of my priority list.

Some thoughts:
- link the required libraries, statically. Probably the easiest solution.
- use some kind of JIT to load the required function dynamically and ensure they're not called from a Qt environment
- provide an alternative version that's built on Qt
- provide the sources, at least of the UI part, so users like me can link the plugin as appropriate on their system.

R.

**Comment by jazz-soft** [comment]
Just FYI: if you are looking for a MIDI player, you can check https://jazz-soft.net/download/midi-player
If you are trying to use a Web View in your own application, you can check how it was done for Electron: https://github.com/jazz-soft/jazz-midi-electron

**Comment by RJVB** [comment]
Thanks, I have external apps capable of playing MIDI content.
