### ISSUE TITLE
Doesn't work on Safari (Mac)

### ISSUE THREAD

**Issue by aik099** [jazz-soft/jazz-soft.github.io#2]
I've downloaded and installed plugin for Mac from https://jazz-soft.net/download/Jazz-Plugin/ page and restarted Safari, but the Jazz Soft plugin isn't recognized by Safari.

I'm using macOS 10.14.2 and Safari 12.0.2.

**Comment by jazz-soft** [comment]
Thanks for the info. That must be some "increased security" issue. Did it work in the older MacOS versions?

**Comment by aik099** [comment]
I have no idea. I only installed it on current macOS/Safari versions.

The plugins were installed in correct location, but maybe they're not activated upon browser restart and full computer restart is needed.

**Comment by jazz-soft** [comment]
Ok, will see what I can do about this...
Will appreciate any additional information.

**Comment by jazz-soft** [comment]
An extension for Mac is now available: https://github.com/jazz-soft/jazz-midi
