### ISSUE TITLE
Random MIDI device id on Firefox 64 on Mac

### ISSUE THREAD

**Issue by aik099** [jazz-soft/jazz-soft.github.io#3]
I've installed these extensions on Firefox:

* Jazz-MIDI extension v1.5.1+: https://addons.mozilla.org/en-US/firefox/addon/jazz-midi/
* Web MIDI API extension: https://addons.mozilla.org/en-US/firefox/addon/web-midi-api/

After that I can see MIDI devices, but the device id is different on each page load. That makes it impossible for user to bookmark device by id for it to be auto-selected later in web page using MIDI devices.

**Comment by jazz-soft** [comment]
I will address this in the next release.
Meanwhile, you can use the device name as an ID

**Comment by jazz-soft** [comment]
It should be fixed in jzz v0.8.8
